mei-yamaji/apple

src/app/Http/Controllers/Auth/AuthenticatedSessionController.php, src/resources/views/auth/login.blade.php, src/resources/views/dashboard.blade.php
=> ログイン時のフラッシュメッセージ実装

src/app/Http/Controllers/ProfileController.php, src/app/Http/Requests/ProfileUpdateRequest.php, src/database/migrations/2025_06_13_043438_add_profile_image_to_users_table.php, src/lang/ja.json, src/resources/views/profile/edit.blade.php, src/resources/views/profile/partials/update-profile-information-form.blade.php
マイページ編集画面のレイアウトの変更と、アイコンの画像を登録できるようにしました！
=> マイページ編集画面の配置変更など

src/app/Http/Controllers/ArticleController.php, src/app/Models/Board.php, src/database/migrations/2025_06_13_135905_create_articles_table.php, src/resources/css/app.css, src/resources/views/dashboard.blade.php, src/resources/views/layouts/app.blade.php, src/routes/web.php
=> ランキング機能の切り替えボタン

src/resources/views/auth/forgot-password.blade.php, src/resources/views/auth/login.blade.php, src/resources/views/auth/register.blade.php, src/resources/views/layouts/guest.blade.php
ログイン画面と新規登録画面のフォームの背景にリンゴを設置＆背景色変更＆文字色変更しました！
=> ログイン画面のUI変更

src/app/Http/Controllers/BoardController.php, src/resources/views/boards/index.blade.php, src/resources/views/boards/show.blade.php, src/routes/web.php
記事の詳細画面の作成と、一覧画面から詳細画面に遷移できるようにルーティングしました！
=> 記事詳細画面作成と遷移

src/resources/views/boards/index.blade.php
記事一覧画面の情報の配置を少し変えて、いいね数と閲覧数の表示場所を用意しました！
=> 記事詳細画面のUI変更

src/app/Http/Controllers/LikeController.php, src/app/Models/Like.php, src/app/Models/User.php, src/database/migrations/2025_06_16_141052_create_likes_table.php, src/package-lock.json, src/package.json, src/resources/views/boards/index.blade.php, src/resources/views/layouts/app.blade.php, src/routes/web.php
記事一覧でのいいね機能を実装しました
・いいねを付ける、削除できる
・一人が複数いいねできないようにした
=> 記事一覧でのいいね機能の実装

src/resources/views/boards/show.blade.php
=> マイページに記事一覧を表示

src/app/Http/Controllers/LikeController.php, src/resources/views/boards/index.blade.php, src/resources/views/boards/show.blade.php, src/routes/web.php
いいねをしても画面上部に行かないように実装しました！(非同期処理)
触ったファイル
src/app/Http/Controllers/LikeController.php
src/resources/views/boards/index.blade.php　いいねボタン(右寄せ)、一番下<script>追加
src/resources/views/boards/show.blade.php　いいねボタン(右寄せ)、一番下<script>追加
src/routes/web.php　いいね関連
=> いいね機能の非同期処理

src/resources/views/boards/index.blade.php
ページネーションを一覧画面に追加した
下が切れないように余白を入れた
src/resources/views/boards/index.blade.php
=> ページネーション一覧画面に追加

src/app/Http/Controllers/Admin/CategoryController.php, src/resources/views/admin/boards/index.blade.php, src/resources/views/admin/categories/create.blade.php, src/resources/views/admin/categories/edit.blade.php, src/resources/views/admin/categories/index.blade.php, src/resources/views/admin/users/index.blade.php, src/resources/views/layouts/admin-sidebar.blade.php, src/resources/views/layouts/admin.blade.php, src/routes/admin.php
=> 管理者画面でカテゴリ編集

src/app/Http/Controllers/ProfileController.php, src/resources/views/boards/index.blade.php, src/resources/views/boards/show.blade.php, src/resources/views/dashboard.blade.php, src/resources/views/profile/edit.blade.php
必要箇所にフラッシュメッセージ追加と、既存のフラッシュメッセージとのデザイン統一をしました。
=> フラッシュメッセージを一通り実装

src/app/Http/Controllers/UserController.php, src/app/Models/User.php, src/resources/views/mypage.blade.php, src/routes/web.php
・マイページに自分の記事とお気に入り記事の切り替えボタンを実装しました
=> Mypagekirikae

src/app/Http/Controllers/FavoriteController.php, src/app/Http/Controllers/ProfileController.php, src/app/Http/Controllers/UserController.php, src/app/Models/User.php, src/app/Notifications/FavoriteNotification.php, src/resources/views/mypage.blade.php, src/resources/views/profile/followers.blade.php, src/resources/views/profile/followings.blade.php, src/resources/views/user/show.blade.php, src/routes/web.php
フォロー/フォロワー数のボタンをマイページに設置
そこからそれぞれのユーザー一覧にが表示でき、そのユーザーのプロフィールにも遷移できるようにした
=> フォローフォロワーボタン作成

src/resources/views/admin/dashboard.blade.php
=> 管理者のダッシュボードUI変更

src/resources/views/components/primary-button.blade.php, src/resources/views/user/show.blade.php
さっきのだとログインできなくなるから、元に戻しました（プライマリーボタン）
=> motomodosi

src/resources/views/user/show.blade.php
・プロフィール画面（他ユーザーのとこのこと）ページネーションないとき下に余白できちゃうのを、ページネーションないときは表示しない、っていうの追記して直しました
=> shitayohaku

src/app/Http/Controllers/UserController.php, src/resources/views/mypage.blade.php
マイページの自分の投稿一覧といいねした記事にページネーションを実装した
=> マイページのいいね記事と自分の投稿にページネーションを実装

src/app/Http/Controllers/BoardController.php, src/resources/views/boards/edit.blade.php, src/resources/views/boards/preview-edit.blade.php, src/routes/web.php
=> Hensyupreview

src/app/Http/Controllers/BoardController.php, src/resources/views/layouts/app.blade.php, src/tailwind.config.js
=> コメントのカウント修正

src/resources/views/boards/edit.blade.php, src/resources/views/boards/preview-edit.blade.php, src/resources/views/comments/edit.blade.php
投稿の編集の戻るボタンUI 
投稿編集プレビューの戻って修正UI 
投稿プレビュー画面と投稿編集プレビュー画面のUIを同じにした
=> ボタンのUI実装＆プレビュー画面のUI実装

src/resources/views/boards/preview-edit.blade.php, src/resources/views/comments/edit.blade.php
コメント編集のUIを投稿編集やプレビュー画面のボタンのUIを変更した
=> コメント編集のUIを変更

src/resources/views/profile/followers.blade.php, src/resources/views/profile/followings.blade.php
〇〇さんがフォロー中と書かれている背景の色を真っ白に変更しました
=> フォローフォロワー欄の色真っ白にした
